#!/bin/bash

SCRIPTS=$(cd `dirname $0` && pwd)
cd "${SCRIPTS}/.."
mkdir -p "./bin"

cd "${SCRIPTS}/../api/openapi"
"./injector.go"
cp "openapi.json" "${SCRIPTS}/../bin/openapi.json"
cp "../CHANGELOG.md" "${SCRIPTS}/../bin/CHANGELOG.md"

