#!/bin/bash

clear
SCRIPTS=$(cd `dirname $0` && pwd)
"${SCRIPTS}/_build-openapi"
"${SCRIPTS}/_build-app"
"${SCRIPTS}/_test-app"
"${SCRIPTS}/_test-api"

cd "${SCRIPTS}/../bin"
"./go-qlueless-assembly-api"
